### ISSUE TITLE
Specify version for yarn and node

### ISSUE THREAD

**Issue by ziyuan-linn** [ml5js/ml5-next-gen#170]
I'm opening this issue after a discussion with @alanvww. We are looking into options such as the `.nvmrc` file to lock the versions of our dev tools.

**Comment by ziyuan-linn** [comment]
@alanvww I just made a draft PR #173. 

I ran the `yarn set version stable` command, setting the yarn version to `4.3.1`. The correct version of Yarn can now be installed through Corepack. ✅

I noted in `package.json` and in the contributing guide that node version 20 (lts) should be used, but I was not able to get `.nvmrc` to work. The `nvm use` command does not seem to recognize the `.nvmrc` file in the project. I noted in `package.json` and in the contributing guide that node version 20 should be used. Please let me know if you know a way to get `.nvmrc` to work.

**Comment by alanvww** [comment]
> @alanvww I just made a draft PR #173.
> 
> I ran the `yarn set version stable` command, setting the yarn version to `4.3.1`. The correct version of Yarn can now be installed through Corepack. ✅
> 
> I noted in `package.json` and in the contributing guide that node version 20 (lts) should be used, but I was not able to get `.nvmrc` to work. The `nvm use` command does not seem to recognize the `.nvmrc` file in the project. I noted in `package.json` and in the contributing guide that node version 20 should be used. Please let me know if you know a way to get `.nvmrc` to work.

Hello Peter, I just checked your PR and looks like the there is a problem with the `.nvmrc` file you create. It is not plain text. 

Can you try run the following with terminal in the project root directory:
```sh
echo "lts/iron" > .nvmrc
```
I think it should fix the problem.

**Comment by ziyuan-linn** [comment]
@alanvww Oh oops, Thank you for pointing it out!

The command is working for macOS now! However, `nvm use` still does not work on my Windows machine. I think `nvm use` without a version number is not supported by `nvm-windows` since there is no mention of it in the usage. I updated the contributing guide accordingly.
